### ISSUE TITLE
Documentation for `excludeMessages` could be clearer

### ISSUE THREAD

**Issue by kaiyoma** [nils-hoyer/cypress-fail-on-console-error#8]
It's not immediately clear from the docs how the value for `excludeMessages` is to be passed or interpreted. I had to use trial and error to figure out that a string will undergo sub-string matching, possibly because these strings are converted to regular expressions? This part is unclear.

Are only strings accepted here, or can regexes be passed as well? If only strings are accepted, but they're being turned into regexes anyway, should this value actually be an array of regexes?

**Comment by nils-hoyer** [comment]
Thank you for your feedback. I extended the docs for config.excludeMessages. Technically changing from string to RegExp is not a problem but I also don't see the need to do so. Feel free to send a PR :-)   

fixed with version 2.0.4:
https://github.com/nils-hoyer/cypress-fail-on-console-error/releases/tag/2.0.4

commit hash: https://github.com/nils-hoyer/cypress-fail-on-console-error/commit/077ba7fdbd4a338166f1646f06a6638c161ac11b
