### ISSUE TITLE
Logic for `excludeMessages` seems a bit wrong: valid errors are being lost

### ISSUE THREAD

**Issue by kaiyoma** [nils-hoyer/cypress-fail-on-console-error#9]
To repro:

1. In your AUT, print two different error strings during a single test (e.g. `"foo"` and `"bar"`)
2. Run a Cypress test with this plugin and notice that both errors are flagged. Great so far
3. Add only one error (`"foo"`) to `excludeMessages`
4. Notice that all errors are being suppressed now. This is wrong: the `"bar"` error should still be appearing

Glancing at the code, this is potentially a problem: https://github.com/nils-hoyer/cypress-fail-on-console-error/blob/9d08faac0bf761d7938311a6aea3a4bafd26eb80/src/index.ts#L105

You're only looking at the first invocation (`spy.args[0][0]`) and making the final decision based on that. What if there are multiple invocations?

(Also `isExludeMessage` is spelled wrong.)

**Comment by kaiyoma** [comment]
There's also the inverse problem too: errors that should be suppressed are still appearing, for basically the same reason. Slightly altering the repro steps from above:

1. In your AUT, print two different error strings during a single test (e.g. `"foo"` and `"bar"`)
2. Run a Cypress test with this plugin and notice that both errors are flagged. Great so far
3. Add only one error (`"bar"`) to `excludeMessages`
4. Notice that all errors are still appearing. This is wrong: only the `"foo"` error should still be appearing

**Comment by nils-hoyer** [comment]
Hey, @kaiyoma, again, thank very much for providing a very detailed report. I just released a new version which fixes that issue. all the best to you. 

fixed with version 2.0.5:
https://github.com/nils-hoyer/cypress-fail-on-console-error/releases/tag/2.0.5

commit hash: https://github.com/nils-hoyer/cypress-fail-on-console-error/commit/4221adaa38dd5ebf04acd2aa62594f3cdeeac839
