### ISSUE TITLE
RegEx not matching as Expected

### ISSUE THREAD

**Issue by Elte156** [nils-hoyer/cypress-fail-on-console-error#91]
## Description

Trying to use the `excludeMessages` config to match against certain console errors. I'm using escape chars on `[` and `]` and it's not working.

## Reproduce

Sample File
```ts
console.error('[alloy] [DataCollector] An error occurred while executing the sendEvent command');
```

Config
```ts
const config = {
  excludeMessages: [
    '\[alloy\] \[DataCollector\] An error occurred while executing the sendEvent command',
  ],
  includeConsoleTypes: [
      consoleType.ERROR,
  ],
};
```

That regex should match the error and ignore it during my cypress test, but it does not. I have to result to:
```ts
'alloy.*DataCollector.*An error occurred while executing the sendEvent command'
```

**Comment by nils-hoyer** [comment]
Hi @Elte156,
thank you for your report. The plugin is using String.match() eg. "foo[bar".match("foo\\[bar") function for comparison. When the RegEx is converted from a string the backslash will get lost. I am wondering your IDE is not complaining on "foo\bar" because it's actually not valid js. To make it work you have use \\ in Javascript. Here are some more Information for you: https://javascript.info/regexp-escaping. I will escaping to the documentation in the next release.
