### ISSUE TITLE
Add documentation for String.match Implementation and special character escaping 

### ISSUE THREAD

**Issue by nils-hoyer** [nils-hoyer/cypress-fail-on-console-error#92]
Hi @Elte156,
thank you for your report. The plugin is using String.match() eg. `"foo[bar".match("foo\\[bar")` function for comparison. When the RegEx is converted from a string the backslash will get lost. I am wondering your IDE is not complaining on "foo\bar" because it's actually not valid js. To make it work you have use `\\` in Javascript. Here are some more Information for you: https://javascript.info/regexp-escaping. I will Add escaping to the documentation in the next release.

_Originally posted by @nils-hoyer in https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/91#issuecomment-1179493242_

**Comment by Elte156** [comment]
Hi @nils-hoyer thanks for the reply.

Here's what my IDE (VSCode) shows in the `index.ts` file when only using one `\`.
![image](https://user-images.githubusercontent.com/6825856/178106213-046d0bd0-e604-4875-be22-d8bd39c8134f.png)
There's no explicit error because `excludeMessages` is typed as `string[]` and the IDE doesn't know any better.

In addition to updating the README about escaping characters, **what about allowing an actual `RegExp[]` type?**
![image](https://user-images.githubusercontent.com/6825856/178106146-f1b3ecda-5653-448f-9e30-b2484de0b12f.png)

**I can pull a PR if you think that's okay.**

**Comment by nils-hoyer** [comment]
I agree with your feature request. With string | RegEx the plugin is still backwards compartible and it's up to the user to choose. A PR is welcome! I appreciate your work @Elte156 !
